### ISSUE TITLE
404 not found on pull

### ISSUE THREAD

**Issue by artooro** [GoogleCloudPlatform/redis-docker#15]
I am trying `gcloud docker -- pull launcher.gcr.io/google/redis3:latest` and get back `Error response from daemon: login attempt to https://appengine.gcr.io/v2/ failed with status: 404 Not Found`

Would this be related to the fact that my container engine cluster isn't able to start the redis PODs as of this morning?

**Comment by jprzychodzen** [comment]
Hi artooro,

I've checked, and I can download image from `launcher.gcr.io/google/redis3:latest`.

Do you still have a problem with that image? If you have any problems with GCP, remember that you can always use a [Support](https://cloud.google.com/support/docs/community). If the issue persists, please consider filling a [bug](https://cloud.google.com/support/docs/issue-trackers). I think this can be [Container Registry issue](https://issuetracker.google.com/issues/new?component=187156&template=0).

**Comment by artooro** [comment]
On container engine the redis pods are still stuck at `Error syncing pod` so trying to figure that out. But I'll contact support if needed.
