### ISSUE TITLE
Docs for launching multiple redis instances with sentinel

### ISSUE THREAD

**Issue by mhr3** [GoogleCloudPlatform/redis-docker#26]
The current docs only mention how to launch a single instance, but in most cases we're interested in HA setup. Would be nice to expand the docs.

**Comment by jprzychodzen** [comment]
Thank you for submitting this feedback. We are currently working on expanding this documentation and are working on adding this enhancement.

**Comment by armandomiani** [comment]
Hello @mhr3, 

We released a Kubernetes application using redis5 container. Could you please check the application README and scripts (https://github.com/GoogleCloudPlatform/click-to-deploy/tree/master/k8s/redis-ha). I'm sure it will be a fit for you. 

Thanks!
