### ISSUE TITLE
Image should follow advice of docker warnings

### ISSUE THREAD

**Issue by mike-marcacci** [GoogleCloudPlatform/redis-docker#36]
On boot, redis writes the following warnings to the console:

> WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

> WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.

Unless this is intentional (ie. they aren't in fact helpful in GKE infrastructure for whatever reason), these changes should probably be added to the image.

These warnings are generated with the latest **redis 3** (6e5460811432) and the latest **redis 4** (3f47963f461e).

**Comment by KadharNiminen** [comment]
There's nothing that can be done here -- This is a host level configuration that can't be modified inside the container (unless it runs in privileged mode).

All warning related to kernel which on host system. All you can do it is enable it manually on all nodes where you run the container if its just docker :
for warning:
> WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.


    sysctl -w net.core.somaxconn=65535



> WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.

    echo never > /sys/kernel/mm/transparent_hugepage/enabled

Go to /etc/rc.local

    $~: sudo vim /etc/rc.local

Add this:

    echo never > /sys/kernel/mm/transparent_hugepage/enabled

or
In case you run it in Kubernetes [there is official doc:](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/)

**Comment by mike-marcacci** [comment]
This is very helpful – thanks for the thorough explanation!
